Repository ryanoasis/nerd-fonts, pull requests merged in 2021-12, with the labels that each got.

#699 font-patcher: Give meaningful error messages on trivial open fails
  font-patcher
Labels: ✨ enhancement

#593 font-patcher: Use correct source font metrics
  font-patcher
Labels: Bug fix

#692 font-patcher: Reintroduce fsType fix
  font-patcher
Labels: ✨ enhancement

#724 font info: Remove references to 'Terminess' from non-Terminus fonts
  patched-fonts/DroidSansMono/font-info.md
  patched-fonts/DroidSansMono/readme.md
  patched-fonts/Ubuntu/Bold-Italic/font-info.md
  patched-fonts/Ubuntu/Bold-Italic/readme.md
  patched-fonts/Ubuntu/Bold/font-info.md
  patched-fonts/Ubuntu/Bold/readme.md
  patched-fonts/Ubuntu/Condensed/font-info.md
  patched-fonts/Ubuntu/Condensed/readme.md
  patched-fonts/Ubuntu/Light-Italic/font-info.md
  patched-fonts/Ubuntu/Light-Italic/readme.md
  patched-fonts/Ubuntu/Light/font-info.md
  patched-fonts/Ubuntu/Light/readme.md
  patched-fonts/Ubuntu/Medium-Italic/font-info.md
  patched-fonts/Ubuntu/Medium-Italic/readme.md
  patched-fonts/Ubuntu/Medium/font-info.md
  patched-fonts/Ubuntu/Medium/readme.md
  patched-fonts/Ubuntu/Regular-Italic/font-info.md
  patched-fonts/Ubuntu/Regular-Italic/readme.md
  patched-fonts/Ubuntu/Regular/font-info.md
  patched-fonts/Ubuntu/Regular/readme.md
  patched-fonts/Ubuntu/font-info.md
  patched-fonts/Ubuntu/readme.md
Labels: :pencil2: documentation

#705 add support for codicons
  font-patcher
  src/glyphs/codicon.ttf
Labels: { ; } new glyph set
