Repository ryanoasis/nerd-fonts, pull requests merged in 2022-09, with the labels that each got.

#798 font-patcher: Correct python module missing message
  font-patcher
Labels: ✨ enhancement

#914 font-patcher: Do not overwrite glyphs that are needed for basic glyphs
  font-patcher
Labels: Bug fix

#794 font-patcher: Allow to specify custom symbolfont with absolute path
  font-patcher
Labels: ✨ enhancement

#793 font-patcher: Allow glyphs with altuni for exactEncoding
  font-patcher
Labels: Bug fix

#833 Add icons for Emacs and Orgmode
  bin/scripts/lib/i_seti.sh
  font-patcher
  src/glyphs/original-source.otf
  src/svgs/emacs.svg
  src/svgs/orgmode.svg
Labels: ❲+❳ add glyph to core set

#862 Add Kotlin icon
  bin/scripts/lib/i_seti.sh
  font-patcher
  src/glyphs/original-source.otf
  src/svgs/kotlin.svg
Labels: ❲+❳ add glyph to core set

#822 install.sh --remove
  install.sh
Labels: ✨ enhancement

#783 Feature: Process TTC files
  font-patcher
Labels: ✨ enhancement

#841 Feature: Add -WindowsCompatibleOnly switch parameter to install.ps1
  install.ps1
Labels: ✨ enhancement, waiting for information
