Repository ryanoasis/nerd-fonts, pull requests merged in 2024-04, with the labels that each got.

#1583 Add Ubuntu Sans
  bin/scripts/lib/fonts.json
  bin/scripts/name_parser/FontnameTools.py
  font-patcher
  readme.md
  src/unpatched-fonts/UbuntuSans/LICENCE.txt
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-Bold.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-BoldItalic.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-Italic.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-Medium.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-MediumItalic.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-Regular.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-SemiBold.ttf
  src/unpatched-fonts/UbuntuSans/Mono/UbuntuSansMono-SemiBoldItalic.ttf
  src/unpatched-fonts/UbuntuSans/README.md
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-Bold.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-BoldItalic.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-Italic.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-Medium.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-MediumItalic.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-Regular.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-SemiBold.ttf
  src/unpatched-fonts/UbuntuSans/Sans/UbuntuSans-SemiBoldItalic.ttf
  src/unpatched-fonts/UbuntuSans/config.cfg
Labels: ❲Aa❳ new font

#1596 FontAwesome: Reorder some glyphs
  bin/scripts/lib/i_fa.sh
  src/glyphs/font-awesome/FontAwesome.otf
  src/glyphs/font-awesome/generate
  src/glyphs/font-awesome/mapping
  src/glyphs/font-awesome/remix
  src/glyphs/font-awesome/remix_mapping
Labels: Bug fix

#1597 Bugfix Ubuntu ligatures
  font-patcher
  src/unpatched-fonts/Ubuntu/README.md
  src/unpatched-fonts/Ubuntu/config.json
Labels: Bug fix

#1613 font-patcher: Allow to rehint some Cascadia glyphs
  bin/scripts/gotta-patch-em-all-font-patcher!.sh
  font-patcher
  src/config.sample.cfg
  src/config.sample.json
  src/unpatched-fonts/3270/config.cfg
  src/unpatched-fonts/BitstreamVeraSansMono/config.cfg
  src/unpatched-fonts/CascadiaCode/config.cfg
  src/unpatched-fonts/CascadiaMono/config.cfg
  src/unpatched-fonts/D2Coding/config.cfg
  src/unpatched-fonts/DaddyTimeMono/config.cfg
  src/unpatched-fonts/DejaVuSansMono/config.cfg
  src/unpatched-fonts/DroidSansMono/config.cfg
  src/unpatched-fonts/FantasqueSansMono/config.cfg
  src/unpatched-fonts/FiraCode/config.cfg
  src/unpatched-fonts/GeistMono/config.cfg
  src/unpatched-fonts/Hack/config.cfg
  src/unpatched-fonts/Hasklig/config.cfg
  src/unpatched-fonts/Hermit/config.cfg
  src/unpatched-fonts/IBMPlexMono/config.cfg
  src/unpatched-fonts/IntelOneMono/config.cfg
  src/unpatched-fonts/Iosevka/config.cfg
  src/unpatched-fonts/IosevkaTerm/config.cfg
  src/unpatched-fonts/IosevkaTermSlab/config.cfg
  src/unpatched-fonts/JetBrainsMono/config.cfg
  src/unpatched-fonts/Lekton/config.cfg
  src/unpatched-fonts/Lekton/config.json
  src/unpatched-fonts/MPlus/config.cfg
  src/unpatched-fonts/MartianMono/config.cfg
  src/unpatched-fonts/Meslo/config.cfg
  src/unpatched-fonts/Monaspace/config.cfg
  src/unpatched-fonts/Monofur/config.cfg
  src/unpatched-fonts/NerdFontsSymbolsOnly/config.cfg
  src/unpatched-fonts/Noto/Sans-Mono/config.cfg
  src/unpatched-fonts/Noto/Sans-Mono/config.json
  src/unpatched-fonts/Noto/Sans/config.cfg
  src/unpatched-fonts/Noto/Sans/config.json
  src/unpatched-fonts/Noto/config.cfg
  src/unpatched-fonts/OpenDyslexic/config.cfg
  src/unpatched-fonts/OpenDyslexic/config.json
  src/unpatched-fonts/Overpass/Mono/config.cfg
  src/unpatched-fonts/Overpass/Mono/config.json
  src/unpatched-fonts/Overpass/Non-Mono/config.cfg
  src/unpatched-fonts/Overpass/Non-Mono/config.json
  src/unpatched-fonts/Overpass/config.cfg
  src/unpatched-fonts/RobotoMono/config.cfg
  src/unpatched-fonts/SourceCodePro/config.cfg
  src/unpatched-fonts/SpaceMono/config.cfg
  src/unpatched-fonts/SpaceMono/config.json
  src/unpatched-fonts/Ubuntu/config.cfg
  src/unpatched-fonts/Ubuntu/config.json
  src/unpatched-fonts/UbuntuMono/config.cfg
  src/unpatched-fonts/UbuntuSans/config.cfg
  src/unpatched-fonts/VictorMono/config.cfg
  src/unpatched-fonts/ZedMono/Extended/config.cfg
  src/unpatched-fonts/ZedMono/Normal/config.cfg
Labels: Bug fix

#1610 Improve bazel icon
  font-patcher
  src/svgs/bazel.sv_
  src/svgs/bazel_nf.svg
  src/svgs/firebase.sv_
  src/svgs/firebase_nf.svg
  src/svgs/icons.tsv
  src/svgs/ruby.sv_
  src/svgs/ruby_nf.svg
Labels: ✨ enhancement
